version: '3.8'

services:
  postgres:
    image: postgres:17.0
    container_name: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nest-app:
    build: .
    container_name: nest-app
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://username:password@postgres:5432/database
    depends_on:
      - postgres

volumes:
  postgres-data:
